"""empty message

Revision ID: 171419346d86
Revises: 684a35f07b6d
Create Date: 2019-03-12 20:34:52.204301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171419346d86'
down_revision = '684a35f07b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'isActive')
    # ### end Alembic commands ###
