"""empty message

Revision ID: 684a35f07b6d
Revises: ade2b33327d5
Create Date: 2019-03-12 16:14:24.048301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '684a35f07b6d'
down_revision = 'ade2b33327d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_column('teacher', 'isActive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('sage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
